#!/usr/bin/env python3
"""Research-sourced comparison pages (Tier-A opportunities from the 200-product
research). Each entry is grounded in a verified label/price data pack and rendered
through the shared compliant renderer. Buy links are Amazon search links carrying
the affiliate tag until direct-merchant programs are approved."""
from urllib.parse import quote
import bb_render
from bb_render import render_compare, compute_score, amz

def mk(slug,name,category,brand_price,per_day,servings,proprietary,label_summary,
       swap_rows,matches,differs,evidence,safety,consult,sources,match_search,bucket):
    swap=sum(s['cost'] for s in swap_rows)
    pct=round((brand_price-swap)/brand_price*100) if brand_price else 0
    verdict='Lower-cost ingredient match' if pct>=40 else 'Partial match' if pct>=15 else 'Important differences'
    ev_dots={'strong':3,'mod':2,'moderate':2,'weak':1,'limited':1}
    avg=sum(ev_dots.get(e['cls'],2) for e in evidence)/len(evidence) if evidence else 2
    d={'slug':slug,'name':name,'category':category,'reviewed':'Jul 2026',
       'brand_price':brand_price,'brand_per_day':per_day,'label_summary':label_summary,'proprietary':proprietary,
       'verdict':verdict,'match_pct':72 if verdict.startswith('Lower') else 55 if verdict.startswith('Partial') else 45,
       'verdict_note':'A pairing of lower-cost generics covers several overlapping ingredients and a similar intended use, for about %d%% less. Some ingredients and exact doses do not carry over.'%pct,
       'swap_rows':swap_rows,'matches':matches,'differs':differs,'evidence':evidence,
       'score':compute_score(pct,proprietary,avg),
       'safety':safety,'consult':consult,'sources':sources,
       'cart_asins':[],'primary_buy':'https://www.amazon.com/s?k='+quote(match_search),'primary_brand':None,'related':[]}
    return d,bucket

HYD_CONSULT=['<b style="color:var(--ink)">Consult a healthcare professional</b> before regular use if you have high blood pressure, or kidney or heart conditions, or diabetes — and use a clinically formulated ORS for infants, older adults, or significant illness-related dehydration.']
FIBER_CONSULT=['<b style="color:var(--ink)">Talk to a doctor or pharmacist first</b> if you are pregnant or nursing, have a swallowing difficulty or a GI condition (bowel narrowing, IBD), have diabetes, or take prescription medication.',
 'See a professional for rectal bleeding, persistent GI symptoms, or unexplained changes in bowel habits — a fiber supplement is not a treatment.']
FIBER_SAFETY='With any psyllium fiber, increase the amount gradually and drink plenty of water to reduce gas, bloating, or choking risk; take it a couple of hours apart from medications, since fiber can affect absorption.'
SLEEP_CONSULT=['<b style="color:var(--ink)">Talk to a healthcare professional</b> before use if you are pregnant or nursing, take sedatives, blood-pressure, or blood-thinner medications, or have a health condition — melatonin and some botanicals can interact with medications.']
GREENS_CONSULT=['<b style="color:var(--ink)">Consult a physician, pharmacist, or registered dietitian</b> before starting if you are pregnant or nursing, on medication (especially blood thinners, thyroid, or blood-sugar drugs), immunocompromised, or managing a health condition.']
CAFF_CONSULT=['<b style="color:var(--ink)">Count all your daily caffeine</b> (coffee, soda, pre-workout) toward a general ~400 mg adult limit, and don’t stack sources. Not for children or anyone pregnant or nursing; consult a professional if you have a heart condition, high blood pressure, anxiety, caffeine sensitivity, or take medications.']

# ---- RESEARCH DATA (filled from verified agent packs, price-checked Jul 2026) ----
RESEARCH=[
 mk('bellway-alternative','Bellway Super Fiber + Fruit','Gut health · fiber',18,'$0.60','1 scoop/day · ~50/tub',False,
    'Organic psyllium husk delivering ~5 g fiber per scoop, plus real-fruit powders and monk-fruit/stevia for flavor (those amounts are not disclosed).',
    [{'name':'Generic organic psyllium husk powder','desc':'~5 g fiber/day','cost':6,'cls':'strong'}],
    ['Both deliver soluble fiber from psyllium husk — the same core ingredient and a similar intended use (daily regularity).','A comparable per-serving fiber amount (~5 g).','Organic psyllium options exist on both sides.'],
    ['Bellway is pre-flavored and sweetened for taste; plain psyllium is unflavored and can be grittier.','The fruit-powder, sweetener, and flavor amounts are not disclosed, so those can’t be matched.','Third-party testing and certifications vary by generic brand — check the label.'],
    [{'name':'Psyllium (soluble fiber)','cls':'strong','note':'Well-studied bulk-forming fiber for regularity.'},{'name':'Added fruit powders','cls':'weak','note':'Amounts undisclosed; no product-specific outcome data.'}],
    FIBER_SAFETY,FIBER_CONSULT,
    [('Bellway product & label — brand and Walmart listing (price checked Jul 2026)','https://getbellway.com/products/super-fiber-fruit-collection',True),
     ('Generic organic psyllium — NOW Foods (iHerb), price Jul 2026','https://www.iherb.com/pr/now-foods-certified-organic-psyllium-husk-powder-12-oz-340-g/21116',True),
     ('Psyllium fiber & regularity — Harvard Health','https://www.health.harvard.edu/heart-health/psyllium-fiber-regularity-and-healthier-lipid-levels',True)],
    'organic psyllium husk powder','Gut, probiotic, omega & fiber'),

 mk('pure-for-men-alternative','Pure for Men Stay Ready Fiber','Gut health · fiber',36,'$1.20','6 caps/day · 120/bottle',True,
    'A proprietary fiber blend — psyllium husk, aloe vera, chia, and flaxseed — at ~750 mg per capsule (~4,500 mg/day). Per-ingredient amounts are not disclosed.',
    [{'name':'Generic psyllium husk capsules','desc':'~6 caps/day','cost':6,'cls':'strong'}],
    ['Both center on psyllium husk — a soluble fiber — for a similar intended use (digestive regularity).','Same swallowable-capsule format taken with water.','A generic psyllium capsule is a lower-cost ingredient match for the blend’s primary fiber.'],
    ['The brand adds aloe, chia, and flaxseed alongside psyllium; plain psyllium does not — so it’s an overlapping-ingredient match, not an identical formula.','The brand uses a proprietary blend, so the psyllium amount can’t be verified or matched exactly.','Aloe’s evidence for regularity is weak; you lose little by dropping it.'],
    [{'name':'Psyllium (soluble fiber)','cls':'strong','note':'First-line, well-studied bulk fiber for regularity.'},{'name':'Flaxseed','cls':'weak','note':'Provides fiber; less consistent than psyllium for regularity.'},{'name':'Chia','cls':'weak','note':'Gel-forming fiber; little direct clinical data.'},{'name':'Aloe vera leaf','cls':'weak','note':'Limited evidence; can cause GI cramping.'}],
    'Take fiber capsules with a full glass of water — too little liquid can cause choking or blockage. Start low and build up; separate from medications by an hour or two.',FIBER_CONSULT,
    [('Pure for Men product — brand & Amazon listing (Jul 2026)','https://www.pureformen.com/products/stay-ready-fiber-capsules',True),
     ('Generic psyllium capsules — NOW Foods (price Jul 2026)','https://www.nowfoods.com/products/supplements/psyllium-husk-caps-500-mg-veg-capsules',True),
     ('Psyllium & regularity — Harvard Health','https://www.health.harvard.edu/heart-health/psyllium-fiber-regularity-and-healthier-lipid-levels',True)],
    'psyllium husk capsules','Gut, probiotic, omega & fiber'),

 mk('peachy-plump-alternative','Peachy Plump Creatine Bites','Fitness · creatine',60,'$2.00','1 serving/day · 30/container',False,
    'Creatine monohydrate gummies at ~5 g per serving (label claim), plus sugar and a gummy base (amounts not disclosed).',
    [{'name':'Creatine monohydrate powder (bulk)','desc':'5 g/day','cost':6,'cls':'strong'}],
    ['Both deliver the same active molecule — creatine monohydrate — at a comparable ~5 g daily target.','A similar intended use (supporting strength and exercise performance).','The powder is a lower-cost ingredient match on the creatine itself.'],
    ['Gummy convenience and flavor vs. unflavored powder you mix into water.','Independent testing across the creatine-gummy category has flagged under-dosing and stability concerns; powder dosing is measured by you and more consistent.','Gummies typically add sugar; the plain powder does not.'],
    [{'name':'Creatine monohydrate','cls':'strong','note':'One of the most-studied sport-nutrition ingredients for strength.'},{'name':'Gummy format','cls':'weak','note':'Stability and actual-delivered-dose over shelf life is a documented question.'}],
    'Creatine monohydrate is generally well tolerated in healthy adults at ~3–5 g/day; mild GI upset or water-weight gain can occur.',
    ['<b style="color:var(--ink)">Talk to a physician or registered dietitian first</b> if you have kidney disease or reduced kidney function, are pregnant or nursing, are under 18, or take medication.'],
    [('Peachy Plump — brand & shop listing ($59.99 / 30 servings, Jul 2026)','https://peachymen.com/products/peachy-plump-creatine-gummies',True),
     ('Creatine monohydrate powder — Nutricost 1 kg / 200 servings (Amazon)','https://www.amazon.com/Nutricost-Creatine-Monohydrate-Micronized-Powder/dp/B01EVVQX9U',True),
     ('Creatine evidence — ISSN position stand','https://jissn.biomedcentral.com/articles/10.1186/s12970-017-0173-z',True)],
    'creatine monohydrate powder micronized','Fitness & performance'),

 mk('pedialyte-alternative','Pedialyte AdvancedCare Plus','Hydration · electrolytes',45,'$1.50','1 packet/day',False,
    'A glucose-electrolyte oral-rehydration powder: ~650 mg sodium, 370 mg potassium, 840 mg chloride, ~10 g sugar per packet, plus a prebiotic (FOS).',
    [{'name':'Generic WHO oral rehydration salts (ORS)','desc':'1 packet/day','cost':11,'cls':'strong'}],
    ['Both are glucose-plus-electrolyte formulas built on the same oral-rehydration (ORS) approach — sodium, potassium, chloride, glucose.','A similar intended use: replacing fluids and electrolytes lost to illness or heavy sweating.','The generic ORS delivers a comparable-to-higher electrolyte load per liter at a fraction of the price.'],
    ['Pedialyte adds a prebiotic (FOS) and comes pre-flavored and sweetened; generic ORS is usually plain.','One Pedialyte packet makes ~16 oz; one ORS packet makes ~1 liter — follow each label, they’re not spoon-for-spoon interchangeable.','Neither lists zinc; some other ORS products add it.'],
    [{'name':'Oral rehydration / electrolytes','cls':'strong','note':'Clinically established when genuinely needed (illness, heavy sweat).'},{'name':'Everyday routine use','cls':'weak','note':'Little benefit for well-hydrated people; water usually suffices.'}],
    'These carry a meaningful sodium (and sugar) load. Use per label directions, and take particular care for infants, older adults, or anyone with a health condition.',HYD_CONSULT,
    [('Pedialyte AdvancedCare Plus — Abbott product/ingredients','https://www.abbottnutrition.com/our-products/pedialyte-advancedcare-plus-powder',True),
     ('Generic WHO ORS — TRIORAL (Amazon, Jul 2026)','https://www.amazon.com/Rehydration-Organization-Poisoning-Electrolyte-Replacement/dp/B00OG8GA7Y',True),
     ('ORS effectiveness — NCBI / PMC review','https://pmc.ncbi.nlm.nih.gov/articles/PMC2845864/',True)],
    'oral rehydration salts ORS WHO formula','Hydration & electrolytes'),

 mk('nuun-instant-alternative','Nuun Instant','Hydration · electrolytes',26,'$0.87','1 stick/day',False,
    'A rehydration stick with ~520 mg sodium, ~150 mg potassium, ~25 mg magnesium, plus cane sugar/dextrose and vitamins C and B12 (exact sugar grams not disclosed).',
    [{'name':'Store-brand electrolyte drink mix','desc':'1 stick/day','cost':6,'cls':'mod'}],
    ['Both deliver sodium and potassium as the primary rehydration minerals, for a similar intended use.','Both are single-serve stick packs mixed into water.','The store-brand option is a lower-cost ingredient match on the key electrolytes.'],
    ['Nuun Instant is glucose-based (cane sugar + dextrose); the store-brand match is often sugar-free, so it lacks that carbohydrate.','Nuun adds magnesium, calcium, and vitamins the leaner store brand may omit.','Sweetener and flavor systems differ (stevia + sugar vs. sucralose).'],
    [{'name':'Electrolytes / rehydration','cls':'strong','note':'Well supported when genuinely losing fluids.'},{'name':'Everyday use','cls':'weak','note':'Plain water usually suffices for well-hydrated people.'}],
    'These add sodium (and sometimes potassium). If you’re on a sodium- or potassium-restricted diet or have kidney, heart, or blood-pressure conditions, check with a professional before regular use.',HYD_CONSULT,
    [('Nuun electrolyte reference — nuunlife.com','https://nuunlife.com/products/nuun-sport-powder',True),
     ('Nuun Instant 8-ct — Walmart (price/sodium, Jul 2026)','https://www.walmart.com/ip/Nuun-Instant-Electrolyte-Drink-Packets-for-Hydration-Vitamin-C-and-B-Lemon-Lime-8-Count-Box/791305053',True),
     ('Great Value electrolyte mix — Walmart (match, Jul 2026)','https://www.walmart.com/ip/Great-Value-Sugar-Free-Watermelon-Electrolytes-Powdered-Drink-Mix-0-8-oz-10-Packets/1192651446',True)],
    'electrolyte powder packets','Hydration & electrolytes'),

 mk('dose-and-co-alternative','Dose & Co Collagen Peptides','Beauty · collagen',60,'$2.00','1 scoop (20 g)/day',False,
    'A single commodity ingredient — 20 g of hydrolyzed bovine collagen peptides (Types I & III) per serving, unflavored, with no added actives.',
    [{'name':'Store-brand bovine collagen peptides','desc':'20 g/day','cost':27,'cls':'mod'}],
    ['Both deliver the same commodity active — hydrolyzed bovine collagen peptides (Types I & III) — at the same 20 g daily dose.','Single-ingredient unflavored powders with no proprietary actives.','A similar intended use (hair, skin & nails / general collagen support).'],
    ['Branding, sourcing story, and packaging differ; the core peptide does not.','Dose & Co sells flavored and vitamin-C/biotin variants the plain store brand doesn’t replicate.','Collagen is an incomplete protein (low in tryptophan) — don’t count it as a complete protein source, either brand.'],
    [{'name':'Collagen for skin','cls':'mod','note':'Some trials suggest support for hydration/elasticity; effects modest.'},{'name':'Collagen for joints','cls':'weak','note':'Mixed, less consistent evidence.'},{'name':'Collagen for hair & nails','cls':'weak','note':'Heavily marketed, little rigorous human data.'}],
    'Hydrolyzed collagen is generally well tolerated; mild digestive upset is the most common report. It is bovine-sourced (not vegan, kosher, or halal).',
    ['<b style="color:var(--ink)">Consult a qualified healthcare professional</b> before use if you are pregnant or nursing, have a kidney condition or a protein-restricted diet, or take medications.'],
    [('Dose & Co Pure Collagen — official product page','https://us.doseandco.com/products/pure-collagen-peptides-unflavored-pouch',True),
     ('Equate grass-fed collagen peptides — Walmart (match, Jul 2026)','https://www.walmart.com/ip/Equate-Grass-Fed-Hydrolyzed-Bovin-Collagen-Peptides-Type-1-3-Dietary-Supplement-Powder-Form-Unflavored-20-oz/5729755719',True),
     ('Collagen & skin — meta-analysis (PMC)','https://pmc.ncbi.nlm.nih.gov/articles/PMC10180699/',True)],
    'bovine collagen peptides unflavored','Beauty, hair, joint & immune'),

 mk('metamucil-alternative','Metamucil Premium Blend','Gut health · fiber',7,'$0.24','1 tsp/day · 114/tub',False,
    'Psyllium husk delivering ~2.4 g soluble fiber per teaspoon, plus orange flavor, stevia, and color (additive amounts not disclosed).',
    [{'name':'Generic psyllium husk powder','desc':'~3.4 g/day','cost':3,'cls':'strong'}],
    ['Both deliver soluble fiber from psyllium husk at a similar per-dose amount.','A similar intended use — daily fiber and regularity.','A lower-cost ingredient match on the core fiber, unflavored and sugar-free.'],
    ['Metamucil adds orange flavor, stevia, and color; the generic is plain and can be grittier.','Metamucil is pre-measured; the generic you measure yourself.','Metamucil markets a "4-in-1" positioning; the generic is fiber only.'],
    [{'name':'Psyllium (soluble fiber)','cls':'strong','note':'Well-studied for regularity; also supports LDL as part of a diet.'}],
    FIBER_SAFETY,FIBER_CONSULT,
    [('Metamucil Premium Blend — brand page (price checked Jul 2026)','https://www.metamucil.com/en-us/products/fiber-powders/metamucil-premium-blend',True),
     ('Generic psyllium — NOW Foods 24 oz (iHerb, $21.31 Jul 2026)','https://www.iherb.com/pr/now-foods-psyllium-husk-powder-24-oz-680-g/21133',True),
     ('Psyllium fiber & regularity — Harvard Health','https://www.health.harvard.edu/heart-health/psyllium-fiber-regularity-and-healthier-lipid-levels',True)],
    'psyllium husk powder','Gut, probiotic, omega & fiber'),

 mk('benefiber-alternative','Benefiber Prebiotic Fiber','Gut health · fiber',6,'$0.19','1 serving/day · 125/bottle',False,
    'Wheat dextrin (soluble prebiotic fiber), ~3 g fiber per 2-tsp serving; unflavored, sugar-free, non-thickening.',
    [{'name':'Store-brand wheat dextrin fiber','desc':'3 g/day','cost':2,'cls':'strong'}],
    ['Both deliver the same active — soluble wheat dextrin, ~3 g fiber per serving.','A similar intended use — a daily prebiotic / soluble-fiber supplement.','Comparable format: unflavored, sugar-free, non-thickening powder.'],
    ['Brand, manufacturing, and testing programs differ; a store brand may require a specific retail channel.','Bottle sizes and serving counts differ — compare per-serving price, not sticker.','Both list under 20 ppm gluten (not certified gluten-free); avoid with a wheat allergy.'],
    [{'name':'Soluble fiber (wheat dextrin)','cls':'mod','note':'Solid overall; its effect on stool output is modest vs psyllium.'},{'name':'Prebiotic effect','cls':'mod','note':'Demonstrated in fermentation studies.'}],
    'Generally well tolerated; may cause temporary gas or bloating when increasing intake — start low and take with adequate water. Contains wheat-derived dextrin (avoid with a wheat allergy).',FIBER_CONSULT,
    [('Benefiber — brand product page (Jul 2026)','https://www.benefiber.com/fiber-supplement-products/benefiber-powder/',True),
     ('Kirkland OptiFiber (same wheat dextrin) — Costco (Jul 2026)','https://www.costco.com/kirkland-signature-optifiber,-26.8-ounces-190-servings.product.100517315.html',True),
     ('Wheat dextrin / soluble fiber evidence — PMC','https://pmc.ncbi.nlm.nih.gov/articles/PMC4415970/',True)],
    'wheat dextrin fiber powder','Gut, probiotic, omega & fiber'),

 mk('liquid-iv-sugar-free-alternative','Liquid I.V. Sugar-Free','Hydration · electrolytes',39,'$1.30','1 stick/day',True,
    'A sugar-free rehydration stick: ~500 mg sodium, ~370 mg potassium, ~4 g allulose, an amino-acid blend, plus vitamins C and B (exact vitamin amounts not disclosed).',
    [{'name':'Store-brand sugar-free electrolyte mix','desc':'1 stick/day','cost':13,'cls':'mod'}],
    ['Both deliver the core hydration electrolytes — sodium and potassium — in a sugar-free single-serve powder.','A similar intended use — mixed into water for everyday hydration.','A lower-cost ingredient match on the electrolyte base.'],
    ['Liquid I.V. adds a proprietary amino-acid + allulose blend and a fuller vitamin profile; store brands carry fewer add-ons.','Electrolyte amounts vary between products — check each label.','Flavor range and stick size differ; store-brand availability may be regional.'],
    [{'name':'Electrolytes / rehydration','cls':'strong','note':'Well supported when genuinely losing fluids.'},{'name':'Everyday use','cls':'weak','note':'Limited benefit over water for well-hydrated people.'}],
    'This carries a meaningful sodium load. If you are on a sodium- or potassium-restricted diet or have kidney, heart, or blood-pressure conditions, check with a professional before regular use.',HYD_CONSULT,
    [('Liquid I.V. ingredients — official','https://www.liquid-iv.com/pages/ingredients',True),
     ('Liquid I.V. Sugar-Free — Amazon (Jul 2026)','https://www.amazon.com/Sugar-Free-Lemon-Lime-14/dp/B0BQ4G7LY8',True),
     ('Great Value sugar-free electrolyte mix — Walmart (match)','https://www.walmart.com/ip/Great-Value-Sugar-Free-Watermelon-Electrolytes-Powdered-Drink-Mix-0-8-oz-10-Packets/1192651446',True)],
    'sugar free electrolyte powder packets','Hydration & electrolytes'),

 mk('gatorlyte-alternative','Gatorade Gatorlyte','Hydration · electrolytes',40,'$1.33','1 stick/day',False,
    'A rapid-rehydration stick: ~490 mg sodium, ~350 mg potassium, ~1,040 mg chloride, calcium and magnesium, and ~10 g sugar per stick.',
    [{'name':'Generic WHO oral rehydration salts (ORS)','desc':'1 packet/day','cost':9,'cls':'strong'}],
    ['Both deliver sodium, potassium, and chloride plus glucose for fluid absorption.','A similar intended use — rehydration after fluid loss from exercise, heat, or illness.','A lower-cost ingredient match on the primary electrolytes.'],
    ['A generic ORS packet makes ~1 L vs Gatorlyte’s ~500 mL — doses per glass are not identical.','Gatorlyte adds calcium and magnesium and consumer flavors; generic ORS is a clinical formula.','They are not interchangeable serving-for-serving — the glucose-sodium ratio differs.'],
    [{'name':'Oral rehydration salts','cls':'strong','note':'WHO-endorsed, extensively studied for dehydration.'},{'name':'Everyday routine use','cls':'weak','note':'Limited benefit for healthy, hydrated people.'}],
    'This carries a meaningful sodium and sugar load. Use per label directions, and take particular care if you have kidney, heart, or blood-pressure conditions or manage blood sugar.',HYD_CONSULT,
    [('Gatorade Gatorlyte — brand page (Jul 2026)','https://www.gatorade.com/gatorlyte',True),
     ('Gatorlyte — Amazon listing (Jul 2026)','https://www.amazon.com/Rehydration-Electrolyte-Specialized-Electrolytes-Scientifically/dp/B0BPN423GH',True),
     ('Generic WHO ORS — TRIORAL (Amazon)','https://www.amazon.com/Rehydration-Organization-Poisoning-Electrolyte-Replacement/dp/B00OG8G9UM',True)],
    'oral rehydration salts ORS WHO formula','Hydration & electrolytes'),

 mk('opti-greens-50-alternative','1st Phorm Opti-Greens 50','Greens · superfood',60,'$2.00','1 serving/day · 30/bag',True,
    'A greens powder built on five proprietary blends (greens, glycemic, phytonutrient, enzymes) plus a 10-strain probiotic — the per-ingredient doses inside the blends are not disclosed.',
    [{'name':'Budget greens powder','desc':'1 scoop/day','cost':27,'cls':'weak'},{'name':'Daily multivitamin','desc':'1/day','cost':2,'cls':'strong'},{'name':'Generic probiotic','desc':'1/day','cost':6,'cls':'mod'}],
    ['The match stack covers the same core categories — a greens/superfood powder, broad vitamins and minerals, and live probiotic strains.','A similar intended use — daily nutritional and gut support.','A lower-cost ingredient match on the ingredient categories.'],
    ['Opti-Greens uses five proprietary blends with undisclosed doses, so its greens and enzyme amounts can’t be matched or verified.','The match is a 2–3 product stack (more steps) rather than one scoop; the strains and enzymes won’t be identical.','Any greens powder is a supplement, not a replacement for eating vegetables.'],
    [{'name':'Greens powders','cls':'weak','note':'Limited evidence they match whole vegetables.'},{'name':'Multivitamin','cls':'strong','note':'Reliably fills common gaps; disclosed doses.'},{'name':'Probiotic','cls':'mod','note':'Strain-specific; effects not universal.'}],
    'Greens powders can be high in vitamin K (relevant on blood thinners); probiotics and enzymes may cause GI upset in some people.',
    ['<b style="color:var(--ink)">Consult a physician, pharmacist, or registered dietitian</b> before starting if you are pregnant or nursing, on medication (especially blood thinners), immunocompromised, or managing a health condition.'],
    [('Opti-Greens 50 — 1st Phorm product page (Jul 2026)','https://1stphorm.com/products/opti-greens-50',True),
     ('Opti-Greens 50 review (blends/doses) — BarBend','https://barbend.com/1st-phorm-opti-greens-50-review/',True),
     ('Best greens powders overview — Forbes Health','https://www.forbes.com/health/supplements/best-greens-powders/',True)],
    'greens powder superfood','Daily multivitamins & greens'),

 mk('gruns-alternative','Grüns Daily Greens','Greens · superfood',56,'$2.00','1 pack/day',True,
    'A daily greens gummy pack: 20+ vitamins and minerals (disclosed), 6 g prebiotic fiber, and a 60+ ingredient fruit/veg/greens blend whose weights are largely proprietary. It contains prebiotic fiber, not probiotics.',
    [{'name':'Budget multivitamin','desc':'1/day','cost':8,'cls':'strong'},{'name':'Budget greens powder (optional)','desc':'1 scoop/day','cost':28,'cls':'weak'}],
    ['A budget multivitamin delivers a similar core set of 20+ vitamins and minerals.','A similar intended use — a once-daily general nutritional-support supplement.','Adding a budget greens gives overlapping greens/superfood ingredients at lower cost.'],
    ['Grüns is a portable no-water gummy; the match is a pill plus an optional powder — less convenient.','Grüns bundles greens, 6 g prebiotic fiber, and adaptogens; a plain multivitamin lacks the fiber and greens.','Grüns discloses vitamin amounts but its greens-blend weights are largely proprietary.'],
    [{'name':'Multivitamin','cls':'strong','note':'Fills common micronutrient gaps; broadly studied.'},{'name':'Greens / superfood','cls':'weak','note':'Not a substitute for whole vegetables.'},{'name':'Prebiotic fiber','cls':'mod','note':'Moderate evidence for digestion; Grüns has no probiotics.'}],
    'Contains iron, vitamin K2, and adaptogens. Vitamin K can interact with blood thinners; iron can be harmful in excess or with iron-overload conditions.',
    ['<b style="color:var(--ink)">Consult a doctor, pharmacist, or registered dietitian</b> first if you are pregnant or nursing, on medication (especially blood thinners), managing a condition, or giving supplements to children.'],
    [('Grüns Daily Greens — Amazon listing (Jul 2026)','https://www.amazon.com/Gruns-Daily-Super-Greens-Gummies-Organic-Spirulina-Chlorella/dp/B0CNQDYFH6',True),
     ('Grüns review — Fortune','https://fortune.com/article/gruns-superfood-gummies-review/',True),
     ('Multivitamin overview — GoodRx','https://www.goodrx.com/multivitamin-and-mineral-supplements',True)],
    'multivitamin','Daily multivitamins & greens'),

 mk('shakeology-alternative','Shakeology','Meal replacement · shake',130,'$4.33','1 serving/day · 30/bag',True,
    'A meal-replacement shake: 16–17 g protein, 6 g fiber, a 2 B CFU probiotic, plus broad vitamins and minerals and a large greens/adaptogen/mushroom blend whose per-ingredient doses are proprietary.',
    [{'name':'Budget plant meal-replacement shake','desc':'1 serving/day','cost':53,'cls':'mod'}],
    ['Overlapping ingredients — plant protein, fiber, a greens/superfood blend, and added vitamins and minerals.','A similar intended use as a once-daily meal-replacement shake.','Comparable protein (16–20 g) and fiber (6–11 g) per serving.'],
    ['Shakeology carries a far broader adaptogen/mushroom/superfood matrix; the budget shake’s blend is narrower.','Shakeology offers a whey option; the budget match shown is plant-only.','Shakeology’s superfood doses are proprietary, so potency can’t be verified head-to-head.'],
    [{'name':'Protein','cls':'strong','note':'Solid for satiety and muscle support.'},{'name':'Greens / superfood blend','cls':'weak','note':'Small blended doses; whole vegetables are better studied.'},{'name':'Probiotic','cls':'mod','note':'Some gut-support evidence; strain-specific.'}],
    'Contains adaptogens (ashwagandha, maca) and mushroom extracts that can interact with medications or conditions.',GREENS_CONSULT,
    [('Shakeology — BODi product page (list price Jul 2026)','https://shop.bodi.com/products/shakeology',True),
     ('Shakeology — Amazon listing','https://www.amazon.com/Shakeology-Superfood-Probiotics-Adaptogens-Chocolate/dp/B0BKCR5X28',True),
     ('Orgain organic meal-replacement (match) — Walmart','https://www.walmart.com/ip/Orgain-Organic-Vegan-Meal-Replacement-Powder-20g-Plant-Based-Protein-Chocolate-2-01lb/119363804',True)],
    'plant meal replacement shake','Daily multivitamins & greens'),

 mk('isalean-alternative','Isagenix IsaLean Shake','Meal replacement · shake',296,'$4.93','2 shakes/day · 14/canister',True,
    'A meal-replacement shake: ~24 g protein, 8 g fiber, 24 vitamins and minerals per serving, plus 9 digestive enzymes and a probiotic — the protein is a proprietary "Myo-IsaLean Complex" whose sub-doses are not broken out.',
    [{'name':'Budget complete-nutrition shake','desc':'2 servings/day','cost':70,'cls':'mod'}],
    ['Overlapping core ingredient — a whey/milk-based protein at a comparable ~15–25 g per serving.','A similar intended use — a convenient meal-replacement shake.','Both provide broad added vitamins and minerals.'],
    ['IsaLean bundles digestive enzymes, a probiotic, and MCT/plant-oil fats a budget shake usually lacks.','Protein grams differ (IsaLean ~24 g vs a budget shake ~15 g); a DIY whey route can match protein but not the enzyme/probiotic blend.','The proprietary protein blend means exact ratios aren’t disclosed.'],
    [{'name':'Protein','cls':'strong','note':'Solid at ~24 g for satiety and muscle support.'},{'name':'Meal-replacement completeness','cls':'mod','note':'Reasonably complete with fiber and 24 micronutrients.'}],
    'Contains milk/dairy (whey, milk protein) — not for a dairy allergy; added fiber and probiotics may cause GI adjustment. Replacing multiple daily meals should be approached carefully.',GREENS_CONSULT,
    [('IsaLean Shake — Isagenix product page (Jul 2026)','https://www.isagenix.com/en-us/shop/weight-management/isalean-protein-shake',True),
     ('IsaLean Shake review — BarBend','https://barbend.com/isagenix-isalean-shake-review/',True),
     ('Kirkland complete nutrition shakes (match) — Costco','https://www.costco.com/kirkland-signature-complete-nutrition-shakes,-8.2-fl.-oz.,-32-pack.product.100399081.html',True)],
    'complete nutrition meal shake','Daily multivitamins & greens'),

 mk('jocko-go-alternative','Jocko GO Energy Drink','Energy · drink',92,'$3.08','1 can/day · 12/pack',True,
    '95 mg caffeine plus L-theanine, alpha-GPC, theobromine, bacopa, B-vitamins, and electrolytes (some amounts not disclosed); zero sugar.',
    [{'name':'Coffee (or a caffeine tablet)','desc':'~95 mg caffeine/day','cost':10,'cls':'strong'}],
    ['The primary active is caffeine — a cup of coffee or a caffeine tablet gives a comparable ~95 mg dose.','A similar intended use — alertness and focus.','A lower-cost ingredient match on the main stimulant.'],
    ['Jocko GO also supplies L-theanine, alpha-GPC, theobromine, bacopa, B-vitamins, and electrolytes that coffee alone does not.','A ready-to-drink flavored can vs. brewing coffee or dosing a tablet.','Some of Jocko GO’s amounts are undisclosed, so the non-caffeine actives can’t be directly compared.'],
    [{'name':'Caffeine','cls':'strong','note':'Strong for short-term alertness and vigilance.'},{'name':'L-theanine','cls':'mod','note':'Moderate for calm focus, paired with caffeine.'},{'name':'Alpha-GPC / bacopa / theobromine','cls':'weak','note':'Weaker evidence at single-serving doses.'}],
    'Total caffeine is the main consideration — count all sources toward a general ~400 mg/day adult limit.',CAFF_CONSULT,
    [('Jocko GO — Jocko Fuel product page (Jul 2026)','https://jockofuel.com/products/jocko-go-energy-drink',True),
     ('Jocko Fuel — Vitamin Shoppe','https://www.vitaminshoppe.com/b/jocko-fuel/food-drinks/drinks/energy-drinks',True),
     ('Caffeine tablets (match) — Walmart','https://www.walmart.com/ip/Prolab-Nutrition-Caffeine-200-mg-100-Tabs/24812008',True)],
    'caffeine tablets','Energy drinks & mixes'),

 mk('five-hour-energy-alternative','5-hour Energy Extra Strength','Energy · shot',80,'$2.62','1 shot/day · 12/pack',True,
    '~230 mg caffeine plus B-vitamins and a proprietary ~1,870 mg "Energy Blend" (taurine, tyrosine, citicoline and more — individual amounts not disclosed); sugar-free.',
    [{'name':'Caffeine tablet (200 mg)','desc':'~200 mg/day','cost':2,'cls':'strong'}],
    ['The active driver is caffeine — a 200 mg tablet is the closest single-ingredient overlap (~230 mg shot vs ~200 mg tablet).','A similar intended use — a fast, portable caffeine boost.','A lower-cost ingredient match on the component that drives the effect.'],
    ['The shot adds B-vitamins, taurine, tyrosine, and citicoline a plain caffeine tablet does not.','Slightly lower caffeine in the tablet, and a liquid shot vs. a pill.','The shot’s blend amounts are proprietary, so total non-caffeine intake can’t be compared.'],
    [{'name':'Caffeine','cls':'strong','note':'Strong for alertness and reaction time.'},{'name':'B-vitamins','cls':'weak','note':'Minimal added benefit unless deficient.'},{'name':'Taurine / amino blend','cls':'weak','note':'Limited, mixed evidence beyond caffeine.'}],
    'One shot is ~230 mg caffeine — count all sources toward a general ~400 mg/day limit and don’t stack shots or pre-workouts.',CAFF_CONSULT,
    [('5-hour Energy caffeine facts — brand','https://5hourenergy.com/blogs/the-feed/5-hour-energy-caffeine-facts',True),
     ('5-hour Energy Extra Strength — Walmart','https://www.walmart.com/ip/5-hour-ENERGY-Shot-Extra-Strength-Sour-Apple-1-93-oz-12-Count/35437566',True),
     ('Caffeine tablets (match) — Amazon','https://www.amazon.com/Nutricost-Caffeine-Pills-Serving-Bottle/dp/B01KKX0GXM',True)],
    'caffeine pills 200mg','Energy drinks & mixes'),

 mk('beam-dream-alternative','Beam Dream Powder','Sleep · calm',34,'$1.13','1 scoop/night · 30/bag',True,
    'A bedtime cocoa with magnesium glycinate, L-theanine, 3 mg melatonin, reishi, apigenin, and nano-hemp — several amounts are not fully broken out on the label.',
    [{'name':'Magnesium glycinate + L-theanine + low-dose melatonin','desc':'1/night','cost':17,'cls':'mod'}],
    ['Both deliver the core sleep-onset stack — magnesium, L-theanine, and low-dose melatonin.','A similar intended use — winding down before bed.','A lower-cost ingredient match on the primary evidence-backed actives.'],
    ['The cocoa drink-mix format and flavors aren’t reproduced by a capsule.','Reishi, apigenin, and nano-hemp/CBD are generally not reproduced in the low-cost match.','Beam’s exact per-ingredient doses are partly undisclosed, so the match is an approximation.'],
    [{'name':'Melatonin','cls':'mod','note':'Moderate for reducing sleep-onset time.'},{'name':'Magnesium','cls':'mod','note':'Moderate, mainly if intake is low.'},{'name':'L-theanine','cls':'weak','note':'Weak-to-moderate for relaxation.'},{'name':'Reishi','cls':'weak','note':'Limited clinical evidence for sleep.'}],
    'Melatonin can cause drowsiness and may interact with sedatives, blood-pressure, or blood-thinner medications; hemp/CBD can interact with other drugs.',SLEEP_CONSULT,
    [('Beam Dream — label & ingredients (Amazon)','https://www.amazon.com/Beam-Ingredients-L-Theanine-Magnesium-Supplement/dp/B0BM4ZVR78',True),
     ('Natural Vitality CALM Sleep (match) — Walmart','https://www.walmart.com/ip/Natural-Vitality-CALM-Sleep-Aid-Capsules-with-Magnesium-Glycinate-Melatonin-and-L-Theanine-60-count/785229559',True),
     ('Stress-Relax Nighttime (alt match) — Amazon','https://www.amazon.com/Stress-Relax-Nighttime-Magnesium-GLYCINATE-Capsules/dp/B0F8PQX431',True)],
    'magnesium glycinate l-theanine melatonin','Sleep & calm'),

 mk('magnesi-om-alternative','Moon Juice Magnesi-Om','Sleep · calm · magnesium',44,'$1.47','1 tsp/day · 30/jar',False,
    '310 mg elemental magnesium from a citrate/gluconate/acetyl-taurinate blend, plus 112 mg L-theanine — all amounts disclosed.',
    [{'name':'Generic magnesium glycinate','desc':'1/day','cost':6,'cls':'mod'},{'name':'L-theanine (optional)','desc':'1/day','cost':3,'cls':'weak'}],
    ['Both deliver supplemental elemental magnesium for the same intended use (rest and relaxation).','The optional L-theanine adds the same second active found in Magnesi-Om.','A lower-cost ingredient match at a fraction of the per-serving price.'],
    ['Different magnesium forms — Magnesi-Om uses a citrate/gluconate/acetyl-taurinate blend; the match uses glycinate (gentler on the gut).','A flavored drink mix vs. capsules.','The L-theanine dose isn’t identical (a 200 mg cap vs 112 mg).'],
    [{'name':'Magnesium','cls':'mod','note':'Moderate, mainly when dietary intake is low.'},{'name':'L-theanine','cls':'weak','note':'Weak-to-moderate for calm and sleep quality.'}],
    'Magnesium (especially citrate) can cause loose stools; high doses may interact with some medications.',
    ['<b style="color:var(--ink)">Consult a healthcare professional</b> before use if you have kidney disease, are pregnant or nursing, or take prescription medication.'],
    [('Magnesi-Om — Moon Juice product page (Jul 2026)','https://moonjuice.com/products/magnesi-om-magnesium-supplement',True),
     ('Magnesi-Om review — Forbes Health','https://www.forbes.com/health/supplements/moon-juice-magnesi-om-review/',True),
     ('Generic magnesium glycinate (match) — Amazon','https://www.amazon.com/Natures-Bounty-Absorption-Supporting-Relaxation/dp/B0DT1JKGPH',True)],
    'magnesium glycinate','Sleep & calm'),

 mk('colonbroom-alternative','ColonBroom Psyllium Fiber','Gut health · fiber',65,'$2.17','1–2 scoops/day · ~60/tub',False,
    'Psyllium husk delivering 3.6 g fiber per scoop, plus crystallized lemon, citric acid, sea salt, and stevia for flavor (those amounts are not disclosed).',
    [{'name':'Generic plain psyllium husk powder','desc':'~one serving/day','cost':8,'cls':'strong'}],
    ['Both deliver soluble fiber from psyllium husk — the same active ingredient and a similar intended use (daily regularity).','Both are water-mixed powders taken once or twice a day.','A lower-cost ingredient match on the fiber itself, at a fraction of the per-serving price.'],
    ['ColonBroom is pre-flavored and sweetened (lemon, stevia, citric acid, salt, color); plain psyllium is unflavored and grittier.','Per-serving fiber differs — ColonBroom discloses 3.6 g/scoop while a generic tablespoon can run ~6 g, so titrate to your own comfort.','ColonBroom is sold on a recurring subscription; the generic tub you buy once and measure yourself.'],
    [{'name':'Psyllium (soluble fiber)','cls':'strong','note':'The most-studied bulk-forming fiber for regularity; AGA-recommended for chronic constipation.'},{'name':'Added flavor & sweetener','cls':'weak','note':'Amounts undisclosed; no product-specific outcome data.'}],
    FIBER_SAFETY,FIBER_CONSULT,
    [('ColonBroom ingredients — brand page (price checked Jul 2026)','https://colonbroom.com/ingredients',True),
     ('Generic psyllium — NOW Foods 24 oz (Amazon, Jul 2026)','https://www.amazon.com/NOW-Supplements-Psyllium-Powder-24-Ounce/dp/B002RWUNYM',True),
     ('Fiber supplements & constipation — AJCN meta-analysis','https://ajcn.nutrition.org/article/S0002-9165(23)03614-6/fulltext',True)],
    'psyllium husk powder','Gut, probiotic, omega & fiber'),

 mk('align-probiotic-alternative','Align Probiotic 24/7 Digestive Support','Gut health · probiotic',30,'$1.00','1 capsule/day · 28/box',False,
    'A single strain — Bifidobacterium longum 35624 — at 1 billion CFU per capsule at manufacture (10 million guaranteed through the best-by date). No prebiotic or other actives.',
    [{'name':'Generic multi-strain probiotic (disclosed CFU)','desc':'1 capsule/day','cost':6,'cls':'mod'}],
    ['Both are once-daily oral probiotic capsules for a similar intended use — supporting general digestive health.','Both disclose live-culture CFU counts on the label.','A generic multi-strain blend is a lower-cost ingredient match that commonly includes Bifidobacterium and Lactobacillus species.'],
    ['Probiotic effects are strain-specific: Align’s data rests on the exact B. longum 35624 strain, which a generic blend may not contain — an important difference.','A higher total CFU in the generic does not equal the same effect; more cells of different strains are not interchangeable with the studied strain.','Strain identity, viability guarantees, and third-party testing vary across generic brands — read the label.'],
    [{'name':'Probiotics (strain-specific)','cls':'mod','note':'Moderate overall; effects apply to specific studied strains, not probiotics in general.'},{'name':'B. longum 35624 for IBS','cls':'mod','note':'Some human trial data over 20+ years; specific to that strain.'}],
    'Probiotics are generally well tolerated; mild, temporary gas or bloating can occur when starting.',
    ['<b style="color:var(--ink)">Talk to a healthcare professional</b> before use if you are immunocompromised, seriously ill, pregnant or nursing, or have an indwelling catheter or central line — this is a supplement, not a treatment.'],
    [('Align — B. longum 35624 strain page','https://www.alignprobiotics.com/en-us/probiotic-101/what-is-bifidobacterium-longum-35624-and-why-is-it-in-align',True),
     ('Align 28-count — Amazon listing (price Jul 2026)','https://www.amazon.com/Align-Probiotics-Supplement-Digestive-Probiotic/dp/B0055OV0MI',True),
     ('trunature multi-strain probiotic (match) — Costco','https://www.costco.com/p/-/trunature-advanced-digestive-probiotic-100-capsules/100387855',True)],
    'multi strain probiotic capsules','Gut, probiotic, omega & fiber'),

 mk('organifi-green-juice-alternative','Organifi Green Juice','Greens · superfood powder',70,'$2.33','1 scoop/day · 30/container',True,
    'A once-daily greens powder built on two proprietary blends (~6.55 g total): moringa, spirulina, chlorella, matcha, ashwagandha, turmeric and more. Individual ingredient amounts are not disclosed.',
    [{'name':'Budget organic greens powder','desc':'1 scoop/day','cost':25,'cls':'weak'},{'name':'Daily multivitamin','desc':'1/day','cost':1,'cls':'mod'}],
    ['The budget greens powder shares core greens — spirulina, chlorella, grasses — for a similar intended use (a daily greens drink).','Adding a multivitamin gives broad vitamin and mineral coverage a greens powder alone does not guarantee.','A lower-cost ingredient match on the overlapping greens, at roughly a third of the price.'],
    ['Organifi hides its greens and adaptogen doses inside proprietary blends, so exact potency can’t be verified or matched.','Organifi adds ashwagandha, matcha, and turmeric a plain budget greens powder may under-supply or omit — an important difference.','A two-product routine is less convenient than one scoop; taste and certifications vary.'],
    [{'name':'Greens powders vs vegetables','cls':'weak','note':'Limited, often brand-funded evidence; not a replacement for eating vegetables.'},{'name':'Multivitamin basics','cls':'mod','note':'Well-established for filling common vitamin and mineral gaps.'},{'name':'Ashwagandha','cls':'mod','note':'Moderate for stress at studied doses — undercut when hidden in a proprietary blend.'}],
    'Greens powders can carry meaningful vitamin K (relevant with blood thinners) and adaptogens like ashwagandha (caution with thyroid, autoimmune, or hormone-sensitive conditions). This is not a weight-loss or disease product.',GREENS_CONSULT,
    [('Organifi Green Juice — brand product page (price Jul 2026)','https://www.organifishop.com/products/green',True),
     ('Organifi ingredient breakdown — BarBend review','https://barbend.com/organifi-green-juice-review/',True),
     ('Can green powders replace vegetables? — Rhitrition','https://www.rhitrition.com/articles/can-green-powders-replace-vegetable-consumption',True)],
    'organic super greens powder','Daily multivitamins & greens'),

 mk('cure-hydration-alternative','Cure Hydration Electrolyte Mix','Hydration · electrolytes',44,'$1.47','1 stick/day · 14/pack',False,
    'A coconut-water-based rehydration stick: 240 mg sodium (pink Himalayan salt + sodium citrate), 300 mg potassium (from coconut water), 4 g sugar (no added sugar), sweetened with stevia and monk fruit.',
    [{'name':'Store-brand sugar-free electrolyte mix','desc':'1 stick/day','cost':12,'cls':'mod'}],
    ['Both deliver sodium and potassium as the primary rehydration minerals, for a similar intended use.','Both are single-serve powder sticks mixed into water, in a no-added-sugar / sugar-free format.','The store-brand option is a lower-cost ingredient match on the key electrolytes.'],
    ['Cure uses a coconut-water base (natural potassium) and pink Himalayan salt; store brands typically use synthetic sodium and potassium citrate.','Cure carries organic, non-GMO, and vegan positioning with stevia and monk fruit; many store brands use artificial sweeteners and flavors.','Exact electrolyte levels, taste, and additives differ — these are similar, not identical, products.'],
    [{'name':'Electrolytes / rehydration','cls':'strong','note':'Well supported when genuinely losing fluids (heat, exercise, illness).'},{'name':'Everyday use','cls':'weak','note':'Plain water usually suffices for well-hydrated people.'}],
    'These add sodium and potassium. If you are on a sodium- or potassium-restricted diet or have kidney, heart, or blood-pressure conditions, check with a professional before regular use.',HYD_CONSULT,
    [('Cure Hydration — brand product page (price Jul 2026)','https://www.curehydration.com/products/hydrating-electrolyte-mix-berry-pomegranate',True),
     ('Great Value sugar-free electrolyte mix (match) — Walmart','https://www.walmart.com/ip/Great-Value-Sugar-Free-Watermelon-Electrolytes-Powdered-Drink-Mix-0-8-oz-10-Packets/1192651446',True),
     ('Cure electrolytes review — Live It Up','https://letsliveitup.com/blogs/electrolytes/cure-electrolytes-review',True)],
    'electrolyte drink mix sugar free','Hydration & electrolytes'),

 mk('viviscal-alternative','Viviscal Women’s Hair Supplement','Beauty · hair',40,'$1.33','2 tablets/day · 60/bottle',True,
    'A proprietary "AminoMar" marine complex at 1,072 mg (component amounts undisclosed), plus biotin 240 mcg, vitamin C 118 mg, zinc 22 mg, and iron 20 mg.',
    [{'name':'Generic marine collagen + biotin','desc':'daily','cost':14,'cls':'weak'},{'name':'Women’s multivitamin (C, zinc, iron)','desc':'1/day','cost':8,'cls':'mod'}],
    ['Overlapping ingredients — biotin, vitamin C, zinc, and marine collagen appear in both the brand and the generic pairing.','A similar intended use — general hair, skin, and nail support.','A lower-cost ingredient match on the disclosed, non-proprietary nutrients.'],
    ['AminoMar is a proprietary marine complex with undisclosed amounts and is not reproduced by the generic pairing — an important difference.','A single generic product may omit the iron dose; matching every nutrient takes a small bundle.','Doses, ingredient forms, and third-party testing differ between products.'],
    [{'name':'Biotin','cls':'weak','note':'No established hair benefit unless you are genuinely biotin-deficient, which is uncommon.'},{'name':'Marine complex (AminoMar)','cls':'weak','note':'A few small, mostly manufacturer-funded studies; independent evidence is limited.'},{'name':'Iron & zinc','cls':'weak','note':'Help hair only if you are actually low; no added benefit at normal levels.'}],
    'This contains 20 mg iron per serving — do not add supplemental iron unless a professional confirms you are iron-deficient; excess iron can be harmful and is a leading cause of pediatric poisoning. Marine-derived ingredients may pose a shellfish-allergy risk.',
    ['<b style="color:var(--ink)">Consult a doctor or pharmacist</b> before use — especially about the iron — if you are pregnant or nursing, post-menopausal, have a shellfish allergy, or take medication.'],
    [('Viviscal Women’s — brand product page (price Jul 2026)','https://www.viviscal.com/products/womans-hair-growth-supplements',True),
     ('Viviscal review & ingredients — Healthline','https://www.healthline.com/health/viviscal',True),
     ('Church & Dwight ingredient disclosure — Viviscal','https://churchdwight.com/ingredient-disclosure/hair-care/viviscal-woman-supplement.aspx',True)],
    'marine collagen biotin hair supplement','Beauty, hair, joint & immune'),

 mk('ritual-synbiotic-alternative','Ritual Synbiotic+','Gut health · synbiotic',54,'$1.80','1 capsule/day · 30/bottle',False,
    'A 3-in-1 capsule: a probiotic blend (LGG + BB-12) at 11 billion CFU, a PreforPro bacteriophage prebiotic at 15 mg, and a tributyrin postbiotic (CoreBiome) at 300 mg — all disclosed.',
    [{'name':'Generic multi-strain probiotic + prebiotic','desc':'1 capsule/day','cost':25,'cls':'mod'}],
    ['Overlapping ingredients — the match contains the same two probiotic species Ritual uses (L. rhamnosus and B. lactis) plus a prebiotic fiber, for a similar intended use.','Both are delivery-designed capsules aimed at the lower gut.','A lower-cost ingredient match pairing probiotics with a prebiotic in one daily capsule.'],
    ['Probiotics are strain-specific: Ritual uses the exact trademarked strains LGG and BB-12, so a same-species generic is not one-to-one evidence — an important difference.','The tributyrin postbiotic is generally not reproduced by a standard probiotic-plus-prebiotic product.','Ritual’s prebiotic is a bacteriophage type (PreforPro); the match usually uses fiber prebiotics like inulin — overlapping use, different mechanism.'],
    [{'name':'Probiotics (LGG, BB-12)','cls':'mod','note':'Among the most-studied strains; findings apply to those specific strains.'},{'name':'Prebiotic','cls':'mod','note':'Generally supports beneficial bacteria.'},{'name':'Postbiotic (tributyrin)','cls':'limited','note':'Emerging, limited human evidence.'}],
    'Generally well tolerated; mild, temporary gas or bloating can occur when starting.',
    ['<b style="color:var(--ink)">Talk to a doctor or registered dietitian</b> before use if you are pregnant or nursing, immunocompromised, seriously ill, or take medication.'],
    [('Ritual Synbiotic+ — brand product page (price Jul 2026)','https://ritual.com/products/synbiotic-plus-for-gut-health',True),
     ('Ritual Synbiotic+ review — Wellness Verge','https://www.wellnessverge.com/ritual-synbiotic-review',True),
     ('Multi-strain probiotic + prebiotic (match) — Amazon','https://www.amazon.com/Probiotics-Formulated-Probiotic-Supplement-Acidophilus/dp/B079H53D2B',True)],
    'multi strain probiotic prebiotic','Gut, probiotic, omega & fiber'),

 mk('ag1-alternative','AG1 by Athletic Greens','Greens · superfood powder',79,'$2.63','1 scoop/day · 30/pouch',True,
    'A once-daily greens-plus-multivitamin powder. Vitamins and minerals are disclosed (e.g. vitamin C ~420 mg, biotin ~330 mcg), but the greens, herb, mushroom, adaptogen, and 7.2 billion CFU probiotic amounts are locked inside proprietary blends.',
    [{'name':'Budget organic greens powder','desc':'1 scoop/day','cost':20,'cls':'weak'},{'name':'Daily multivitamin','desc':'1/day','cost':12,'cls':'mod'},{'name':'Multi-strain probiotic','desc':'1/day','cost':10,'cls':'mod'}],
    ['The stack covers the same three categories AG1 bundles — a greens powder, broad vitamin and mineral coverage, and a daily probiotic — for a similar intended use.','A multivitamin can supply comparable, clearly-labeled doses of the same core vitamins and minerals AG1 lists.','A lower-cost ingredient match on the overlapping components, at a fraction of the per-serving price.'],
    ['AG1 hides its greens, herb, mushroom, adaptogen, and probiotic amounts in proprietary blends, so per-ingredient potency can’t be verified or matched exactly.','Convenience differs — one AG1 scoop versus a powder plus two capsules; third-party testing also varies (AG1 is NSF Certified for Sport).','Exact strain lists, CFU counts, and superfood ratios differ between products — important differences to weigh.'],
    [{'name':'Greens powders vs vegetables','cls':'weak','note':'Limited evidence; not a substitute for eating vegetables.'},{'name':'Multivitamin basics','cls':'mod','note':'Reliably fills common micronutrient gaps.'},{'name':'Probiotic','cls':'mod','note':'Moderate and strain-specific; effects don’t generalize across products.'}],
    'Greens powders can be high in vitamin K (relevant with blood thinners) and may cause bloating. This is not a treatment for any condition.',GREENS_CONSULT,
    [('AG1 — ingredients & proprietary blends (Live It Up)','https://letsliveitup.com/blogs/supergreens/ag1-ingredients',True),
     ('AG1 label — NIH Dietary Supplement Label Database','https://dsld.od.nih.gov/label/262237',True),
     ('Budget probiotic component (match) — Amazon','https://www.amazon.com/Amazon-Brand-Probiotic-Vegetarian-Capsules/dp/B07CZZMFGQ',True)],
    'organic super greens powder','Daily multivitamins & greens'),

 mk('vital-proteins-alternative','Vital Proteins Collagen Peptides','Beauty · collagen',43,'$1.53','2 scoops (20 g)/day · ~28/tub',False,
    'A single commodity ingredient — 20 g of hydrolyzed bovine collagen peptides (Types I & III) per serving, unflavored. The standard tub has no added hyaluronic acid or vitamin C.',
    [{'name':'Store-brand bovine collagen peptides','desc':'20 g/day','cost':19,'cls':'mod'}],
    ['Both deliver the same commodity active — hydrolyzed bovine collagen peptides (Types I & III) — at the same 20 g daily dose.','Both are unflavored single-ingredient powders that mix into liquids, for a similar intended use.','A lower-cost ingredient match delivering the same collagen dose at a materially lower cost per gram.'],
    ['Serving sizes differ — Vital Proteins is 20 g/scoop while the match is often labeled ~11 g, so measure to match and a tub lasts longer per gram.','Sourcing and certification claims differ (grass-fed marketing; an NSF Certified for Sport version) — verify third-party testing on any store brand.','Collagen is an incomplete protein (low in tryptophan) — don’t count it as a sole protein source, either brand.'],
    [{'name':'Collagen for skin','cls':'mod','note':'Moderate but mixed; effects shrink in higher-quality, non-industry-funded trials.'},{'name':'Collagen for joints','cls':'weak','note':'Weak-to-emerging; some support at ~5 g/day over 12+ weeks.'},{'name':'Collagen for hair & nails','cls':'weak','note':'Limited direct human evidence.'}],
    'Hydrolyzed collagen is generally well tolerated; mild digestive upset is the most common report. It is bovine-sourced (not vegan, kosher, or halal).',
    ['<b style="color:var(--ink)">Consult a qualified healthcare professional</b> before use if you are pregnant or nursing, have a kidney condition or a protein-restricted diet, or take medications.'],
    [('Vital Proteins Collagen Peptides 20 oz — Walmart (price/size, Jul 2026)','https://www.walmart.com/ip/Vital-Proteins-Collagen-Peptides-Supplement-Powder-Unflavored-20-oz/350254837',True),
     ('BulkSupplements bovine collagen peptides 1 kg (match)','https://www.walmart.com/ip/BulkSupplements-Collagen-Peptides-Powder-11g-per-Serving-1-Kilogram-2-2-lbs-91-Servings/603229742',True),
     ('Collagen & skin aging — systematic review, Am J Medicine (2025)','https://www.amjmed.com/article/S0002-9343(25)00283-9/abstract',True)],
    'bovine collagen peptides unflavored','Beauty, hair, joint & immune'),

 mk('seed-ds01-alternative','Seed DS-01 Daily Synbiotic','Gut health · synbiotic',50,'$1.67','2 capsules/day · 60/bottle',False,
    'A 2-in-1 synbiotic: a 24-strain probiotic blend totaling 53.6 billion AFU, plus a ~400 mg Indian-pomegranate polyphenol prebiotic. The specific strains are proprietary and per-strain counts are not disclosed.',
    [{'name':'Generic multi-strain probiotic (disclosed CFU) + prebiotic','desc':'1 capsule/day','cost':18,'cls':'mod'}],
    ['Both are multi-strain probiotics paired with a prebiotic, for a similar intended use (general digestive and gut support).','Overlapping ingredient categories — Lactobacillus and Bifidobacterium-family strains plus a prebiotic.','The lower-cost match discloses its total CFU (e.g. 50 billion), enabling a like-for-like potency comparison at a lower monthly cost.'],
    ['Probiotics are strain-specific: the generic’s strains are not Seed’s exact 24 branded strains, so outcomes tied to those specific strains may not carry over — an important difference.','Labeling differs — Seed reports AFU (active fluorescent units) while the match reports CFU; these are measured differently and aren’t directly interchangeable.','Seed’s Indian-pomegranate polyphenol prebiotic and nested-capsule delivery are proprietary and not replicated by a fiber-based generic.'],
    [{'name':'Probiotics (strain-specific)','cls':'mod','note':'Moderate; benefits don’t transfer automatically between products.'},{'name':'Prebiotic','cls':'mod','note':'Reasonable support for supporting gut microbiota.'}],
    'Generally well tolerated; transient gas or bloating can occur when starting — many people ease in with one capsule for the first few days.',
    ['<b style="color:var(--ink)">Talk to a healthcare professional</b> before use if you are immunocompromised, pregnant or nursing, seriously ill, or managing a medical condition.'],
    [('Seed DS-01 — brand product page (price Jul 2026)','https://seed.com/daily-synbiotic',True),
     ('Seed DS-01 — formulation & AFU help doc','https://help.seed.com/en-US/articles/ds-01-daily-synbiotic-295557',True),
     ('InnovixLabs multi-strain probiotic (match) — Amazon','https://www.amazon.com/InnovixLabs-Multi-Strain-Probiotic-Billion-Probiotics/dp/B00X4U2NDK',True)],
    'multi strain probiotic prebiotic','Gut, probiotic, omega & fiber'),

 mk('ritual-multivitamin-alternative','Ritual Essential for Women 18+','Daily multivitamin',30,'$1.00','2 capsules/day · 60/bottle',False,
    'A focused 9-nutrient "fill the gaps" formula, all disclosed: omega-3 DHA 350 mg (algal), vitamin D3 2,000 IU, B12 (methyl) 8 mcg, folate 1,000 mcg DFE, iron 18 mg, vitamin K2 90 mcg, vitamin E 7 mg, boron 0.7 mg, magnesium 32 mg.',
    [{'name':'Generic women’s multivitamin with iron','desc':'1/day','cost':2,'cls':'mod'},{'name':'Vegan algal DHA','desc':'1/day','cost':13,'cls':'mod'}],
    ['Overlapping ingredients — both supply iron, vitamin D, B12, folate, vitamin E, vitamin K, and a DHA dose in a similar range.','A similar intended use — a once-daily women’s multivitamin plus omega-3 to help fill common dietary gaps.','A lower-cost ingredient match reaching comparable nutrient coverage at a lower monthly cost.'],
    ['Ritual is a deliberately narrow 9-nutrient formula (it omits nutrients most women already get); a generic one-a-day includes a broader list — different design, not a like-for-like panel.','Ritual uses a delayed-release capsule and specific methylated/chelated forms plus algal (vegan) DHA; generics vary in forms and are often not vegan.','Ritual is USP-verified and vegan; a generic multi plus fish-oil pairing may not carry the same third-party verification.'],
    [{'name':'Multivitamin (fills gaps)','cls':'mod','note':'Solid for covering dietary shortfalls; broad disease-prevention benefit is limited.'},{'name':'Individual nutrients','cls':'weak','note':'Help mainly when you are actually low or have elevated need.'},{'name':'Omega-3 DHA','cls':'mod','note':'Moderate for certain heart, brain, and eye markers.'}],
    'Contains 18 mg iron — keep away from children (iron-containing products are a leading cause of pediatric poisoning), and don’t add supplemental iron unless a professional confirms you need it.',
    ['<b style="color:var(--ink)">Consult a physician, pharmacist, or registered dietitian</b> before use — especially about iron — if you are pregnant, nursing, planning pregnancy, take blood thinners (note vitamin K2), or manage a health condition.'],
    [('Ritual Essential for Women 18+ — brand page (price Jul 2026)','https://ritual.com/products/essential-for-women-multivitamin',True),
     ('Ritual vitamins — dietitian review (Healthline)','https://www.healthline.com/nutrition/ritual-vitamins-a-dietitians-review',True),
     ('Equate One Daily Women’s multivitamin (match) — Walmart','https://www.walmart.com/ip/Equate-One-Daily-Women-s-Tablets-Multivitamin-Multimineral-Supplement-100-Count/10324635',True)],
    'womens multivitamin with iron algal dha','Daily multivitamins & greens'),

 mk('lmnt-alternative','LMNT Recharge Electrolyte Mix','Hydration · electrolytes',39,'$1.30','1 stick/day · 30/box',False,
    'A zero-sugar electrolyte stick with a distinctively high sodium load, all disclosed: sodium 1,000 mg, potassium 200 mg, magnesium 60 mg, sweetened with stevia.',
    [{'name':'Table salt + Morton Lite Salt (potassium)','desc':'to taste','cost':2,'cls':'strong'},{'name':'Magnesium malate powder','desc':'~60 mg/day','cost':5,'cls':'mod'}],
    ['The same core minerals — sodium chloride, potassium chloride, and magnesium — can be dosed to the exact same milligram targets (1,000 / 200 / 60 mg).','A similar intended use: fluid and electrolyte replacement.','A lower-cost ingredient match on the electrolyte profile at a fraction of the per-serving cost.'],
    ['LMNT’s 1,000 mg sodium per serving is distinctive — roughly 2–4× many competitors; a DIY match hits it, but it is a lot of sodium and not for everyone.','LMNT is pre-measured, dissolves cleanly, and is formulated/flavored for you; a DIY mix needs accurate weighing and tastes saltier or grittier.','LMNT’s natural flavors and stevia are proprietary; a DIY version approximates but is not identical in taste.'],
    [{'name':'Electrolytes when needed','cls':'strong','note':'Strong for heavy sweat, endurance, heat, or low-carb/fasting states.'},{'name':'Everyday routine use','cls':'weak','note':'Little benefit for well-hydrated people on a normal diet.'}],
    'The 1,000 mg sodium per serving is high. Added potassium can also matter for some people.',
    ['<b style="color:var(--ink)">Consult a physician, pharmacist, or registered dietitian</b> before regular use if you have high blood pressure, kidney disease, or heart conditions, or take potassium-affecting medication (ACE inhibitors, ARBs, potassium-sparing diuretics).'],
    [('LMNT Recharge — brand product page (price Jul 2026)','https://drinklmnt.com/products/lmnt-recharge-electrolyte-drink',True),
     ('LMNT full ingredient disclosure','https://drinklmnt.com/pages/ingredients',True),
     ('Morton Lite Salt — potassium source (match) — Amazon','https://www.amazon.com/Morton-Salt-Lite-11/dp/B00KPX1B6Y',True)],
    'electrolyte drink mix high sodium sugar free','Hydration & electrolytes'),

 mk('olly-probiotic-alternative','OLLY Probiotic + Prebiotic Gummy','Gut health · probiotic',13,'$0.43','1 gummy/day · 30/bottle',False,
    'A chewable probiotic gummy: Bacillus coagulans (MTCC 5856) at 500 million CFU, a 1.5 g prebiotic blend (FOS, inulin, xylitol), and 2 g of added sugar per gummy.',
    [{'name':'Generic Bacillus coagulans capsule (higher CFU)','desc':'1/day','cost':12,'cls':'mod'}],
    ['Both deliver Bacillus coagulans as the probiotic organism, for a similar intended use (everyday digestive support).','A lower-cost ingredient match on the same probiotic species at a comparable monthly cost.','Both are once-daily formats.'],
    ['This is more about format than price — the capsule is sugar-free while the gummy adds 2 g sugar per day.','OLLY discloses a low 500 million CFU; a plain capsule commonly discloses far more (e.g. 6 billion).','OLLY bundles prebiotic fiber the plain capsule doesn’t, and strains are not identical, so effects are not interchangeable — important differences.'],
    [{'name':'Probiotics (strain-specific)','cls':'mod','note':'Moderate; benefits shown for one strain don’t transfer to another.'},{'name':'Bacillus coagulans','cls':'mod','note':'Some clinical data for digestive support.'}],
    'Generally well tolerated; mild gas or bloating can occur when starting.',
    ['<b style="color:var(--ink)">Talk to a healthcare professional</b> before use if you are pregnant or nursing, immunocompromised, on antibiotics, or managing a medical condition.'],
    [('OLLY Probiotic + Prebiotic Fiber Gummy — Walmart (price Jul 2026)','https://www.walmart.com/ip/OLLY-Probiotic-Prebiotic-Fiber-Gummy-Digestive-Gut-Health-Supplement-Peach-30-Ct/109791149',True),
     ('OLLY Probiotic + Prebiotic — Amazon listing','https://www.amazon.com/Balanced-Supplement-Prebiotic-Probiotic-Packaging/dp/B012RFVHSO',True),
     ('Swanson Bacillus coagulans 6 billion CFU (match) — Amazon','https://www.amazon.com/Swanson-Lactobacillus-Sporogenes-Bacillus-Coagulans/dp/B00J03Z4UO',True)],
    'bacillus coagulans probiotic capsules','Gut, probiotic, omega & fiber'),

 mk('nutrafol-alternative','Nutrafol Women’s Hair Supplement','Beauty · hair',79,'$2.63','4 capsules/day · 120/bottle',True,
    'Disclosed vitamins (biotin ~2,500 mcg, zinc ~25 mg, vitamin A, C, D, selenium) plus a proprietary 2,130 mg "Synergen Complex" (marine collagen, saw palmetto, Sensoril ashwagandha, curcumin, tocotrienols, hyaluronic acid) and a second proprietary "Nutrafol Blend" — the per-ingredient amounts in both blends are not disclosed.',
    [{'name':'Generic hair-skin-nails combo (collagen, saw palmetto, biotin, keratin, HA)','desc':'daily','cost':28,'cls':'weak'},{'name':'Generic ashwagandha (optional)','desc':'1/day','cost':10,'cls':'mod'}],
    ['Overlapping ingredients — marine collagen, saw palmetto, biotin, hyaluronic acid, and keratin appear in both, for a similar intended use (hair, skin & nails support).','Both are once-daily oral supplements sold without a prescription.','A lower-cost ingredient match delivers several of the same headline actives at a fraction of the monthly cost.'],
    ['Nutrafol’s Synergen Complex and Nutrafol Blend are proprietary, so per-ingredient amounts are undisclosed and can’t be reproduced or verified — an important difference.','Nutrafol uses specific standardized/branded forms (USPlus saw palmetto, Sensoril ashwagandha, BCM-95 curcumin, EVNolMax tocotrienols); generics use unstandardized forms and often omit ashwagandha, curcumin, and tocotrienols.','Nutrafol adds extras (resveratrol, capsicum, piperine, horsetail, amino acids, added vitamins) not all present in one low-cost match.'],
    [{'name':'Biotin','cls':'weak','note':'No established hair benefit unless you are genuinely biotin-deficient.'},{'name':'Saw palmetto','cls':'weak','note':'Limited/emerging evidence for hair; not conclusive.'},{'name':'Ashwagandha','cls':'mod','note':'Moderate for stress; not specifically for hair.'},{'name':'Marine collagen','cls':'weak','note':'Weak evidence for hair; the brand’s own trials are manufacturer-funded.'}],
    'Saw palmetto is hormonally active (affects DHT) — not recommended in pregnancy or nursing. High-dose biotin can skew some lab tests (thyroid, troponin). Sudden or patchy hair loss warrants a professional evaluation.',
    ['<b style="color:var(--ink)">Consult a physician or pharmacist</b> before use if you are pregnant, nursing, on hormone therapy or blood thinners, or managing a medical or hormonal condition.'],
    [('Nutrafol — ingredients page','https://nutrafol.com/ingredients/',True),
     ('Nutrafol Core for Women — product/price (Jul 2026)','https://nutrafol.com/nutrafol-core-for-women/',True),
     ('Generic collagen + saw palmetto + biotin combo (match) — Amazon','https://www.amazon.com/Collagen-10000mcg-Keratin-Palmetto-Hyaluronic/dp/B0B3GBJJGW',True)],
    'hair skin nails saw palmetto collagen biotin','Beauty, hair, joint & immune'),

 mk('native-path-alternative','NativePath Collagen Peptides','Beauty · collagen',50,'$1.67','2 scoops (20 g)/day · 25/tub',False,
    'A single commodity ingredient — 10 g of hydrolyzed grass-fed bovine collagen peptides (Types I & III) per scoop (20 g at two scoops), unflavored, no added co-factors.',
    [{'name':'Store-brand bovine collagen peptides','desc':'20 g/day','cost':19,'cls':'mod'}],
    ['Both deliver the same commodity active — hydrolyzed bovine collagen peptides (Types I & III) — at a comparable ~20 g daily dose.','Both are unflavored powders mixed into liquid, for a similar intended use (skin, hair & nails).','A lower-cost ingredient match at a materially lower cost per gram.'],
    ['NativePath markets grass-fed, pasture-raised sourcing and brand testing; a store brand may not carry identical sourcing claims — an important difference, not equivalence.','NativePath pushes multi-tub "stock up" bundles to lower the per-tub price; the generic competes on plain per-gram cost.','Collagen is an incomplete protein (low in tryptophan) — don’t count it as a sole protein source, either brand.'],
    [{'name':'Collagen for skin','cls':'mod','note':'Moderate but mixed; several independent studies found no significant benefit.'},{'name':'Collagen for joints','cls':'weak','note':'Limited, mixed evidence.'},{'name':'Collagen for hair & nails','cls':'weak','note':'Limited controlled evidence.'}],
    'Hydrolyzed collagen is generally well tolerated; mild digestive upset is the most common report. It is bovine-sourced (not vegan, kosher, or halal).',
    ['<b style="color:var(--ink)">Consult a qualified healthcare professional</b> before use if you are pregnant or nursing, have a kidney condition or a protein-restricted diet, or take medications.'],
    [('NativePath Collagen Peptides — Amazon listing (price Jul 2026)','https://www.amazon.com/NativePath-Collagen-Protein-Powder-Certified/dp/B076PTJBYS',True),
     ('BulkSupplements bovine collagen peptides (match) — Amazon','https://www.amazon.com/BulkSupplements-com-Collagen-Peptides-Powder-Supplements/dp/B015YG2N2C',True),
     ('Hydrolyzed collagen & skin — meta-analysis (PMC)','https://pmc.ncbi.nlm.nih.gov/articles/PMC10773595/',True)],
    'bovine collagen peptides unflavored','Beauty, hair, joint & immune'),

 mk('bloom-greens-alternative','Bloom Nutrition Greens & Superfoods','Greens · superfood powder',35,'$1.17','1 scoop/day · 30/tub',True,
    'A once-daily greens powder of 38 ingredients grouped into ~7 proprietary blends (greens, fruit & veggie, pre/probiotic, adaptogen, digestive enzyme, fiber, antioxidant). Only blend totals are shown; per-ingredient amounts and probiotic CFU are not disclosed.',
    [{'name':'Budget super-greens powder','desc':'1 scoop/day','cost':16,'cls':'weak'},{'name':'Daily multivitamin','desc':'1/day','cost':1,'cls':'mod'}],
    ['Overlapping ingredients — both deliver core greens (spirulina, chlorella, grasses) plus fruit and veggie powders, for a similar intended use (a daily greens drink).','Adding a multivitamin gives standardized, disclosed vitamin and mineral doses the greens powder alone lacks.','A lower-cost ingredient match at roughly half the price.'],
    ['Bloom uses proprietary blends, so individual ingredient amounts and probiotic CFU are undisclosed — you can’t verify potency; the match’s multivitamin at least lists exact amounts.','Bloom’s adaptogen (~100 mg total) and probiotic totals appear low, so neither option should be assumed to deliver a clinically meaningful dose.','Flavor, mixability, and formulation differ — the match is not identical.'],
    [{'name':'Greens powders vs vegetables','cls':'weak','note':'Limited evidence; a small scoop does not replace whole vegetables.'},{'name':'Multivitamin basics','cls':'mod','note':'Solid for covering common vitamin and mineral gaps.'},{'name':'Digestive enzymes','cls':'limited','note':'Limited evidence of meaningful benefit in healthy people.'}],
    'Greens powders can interact with medications — notably vitamin K from leafy greens with blood thinners, and adaptogens (licorice, rhodiola, ginseng) with blood-pressure, blood-sugar, or hormone drugs. This is not a treatment for any condition.',GREENS_CONSULT,
    [('Bloom Greens & Superfoods — brand page (price Jul 2026)','https://bloomnu.com/products/greens-superfoods',True),
     ('Bloom Greens ingredient breakdown — BarBend review','https://barbend.com/bloom-greens-review/',True),
     ('Bloom Greens — Amazon listing','https://www.amazon.com/Bloom-Nutrition-Super-Greens-Powder-Smoothie-Juice-Mix/dp/B08PQ4SH4G',True)],
    'super greens powder','Daily multivitamins & greens'),

 mk('hydrant-alternative','Hydrant Hydrate Electrolyte Mix','Hydration · electrolytes',37,'$1.23','1 stick/day · 30/pack',False,
    'A single-serve stick with 260 mg sodium, 200 mg potassium, 30 mg magnesium, 2 mg zinc, and 4 g cane sugar, flavored with real fruit juice powder — all disclosed.',
    [{'name':'Store-brand electrolyte drink mix','desc':'1 stick/day','cost':12,'cls':'mod'}],
    ['Overlapping core ingredients — both deliver sodium and potassium as the primary electrolytes, for a similar intended use (daily fluid replacement).','Both are single-serve powder sticks mixed into water.','The store-brand packet is a lower-cost ingredient match covering the main electrolyte function at a fraction of the per-serving price.'],
    ['Hydrant adds magnesium and zinc and uses real cane sugar and juice; many store-brand packets are sugar-free and may omit magnesium or zinc — check the label.','Sodium and potassium amounts per stick differ by product and flavor, so electrolyte levels are not identical.','Taste, flavor range, and "no artificial sweetener" positioning differ.'],
    [{'name':'Electrolytes when needed','cls':'strong','note':'Well supported for heat, exercise, or illness-related fluid loss.'},{'name':'Everyday use','cls':'weak','note':'Plain water usually suffices for well-hydrated people.'}],
    'Added sodium and potassium matter for people on sodium- or potassium-restricted diets. Use per label directions.',HYD_CONSULT,
    [('Hydrant Hydrate — brand product page (price Jul 2026)','https://www.drinkhydrant.com/products/hydration-mix',True),
     ('Hydrant Hydrate — Amazon listing','https://www.amazon.com/Hydration-Electrolyte-Dehydration-Recovery-Ingredients/dp/B07SB6DRRM',True),
     ('Great Value electrolyte mix (match) — Walmart','https://www.walmart.com/browse/food/electrolyte-powders/great-value/976759_976782_5795119_5534309',True)],
    'electrolyte drink mix packets','Hydration & electrolytes'),

 mk('just-thrive-alternative','Just Thrive Probiotic & Antioxidant','Gut health · probiotic',50,'$1.67','1 capsule/day · 30/bottle',True,
    'A 100% spore-based blend totaling ~3 billion CFU across four Bacillus strains — B. subtilis HU58, B. coagulans SC-208, B. clausii SC-109, and B. indicus HU36 (an antioxidant-producing strain). The per-strain CFU split is not disclosed.',
    [{'name':'Generic Bacillus spore probiotic (disclosed CFU)','desc':'1 capsule/day','cost':21,'cls':'mod'}],
    ['Overlapping ingredients — both are 100% Bacillus spore-forming probiotics sharing three of the four strain species (B. subtilis, B. coagulans, B. clausii).','A similar intended use (daily digestive and gut support), both shelf-stable and acid-resistant.','A lower-cost ingredient match that discloses a higher labeled CFU per capsule.'],
    ['The exact branded spore strains aren’t reproduced — HU58, HU36, SC-208, and SC-109 are proprietary, and probiotic effects are strain-specific, so a same-species generic may not deliver identical results.','The generic lacks B. indicus HU36, the antioxidant-producing strain that distinguishes Just Thrive — so that feature is not matched.','Higher labeled CFU in the generic doesn’t equal an equivalent effect given different strains.'],
    [{'name':'Spore probiotics (strain-specific)','cls':'mod','note':'Moderate/emerging; data on one strain does not transfer to another.'}],
    'Generally well tolerated; transient bloating or GI changes can occur when starting.',
    ['<b style="color:var(--ink)">Talk to a healthcare professional</b> before use if you are pregnant or nursing, immunocompromised, seriously ill, or take medication.'],
    [('Just Thrive Probiotic & Antioxidant — brand page (price Jul 2026)','https://justthrivehealth.com/products/probiotic',True),
     ('Biome Ultra spore probiotic (match) — Amazon','https://www.amazon.com/Biome-Ultra-ProbioSEB-CSC3-caps/dp/B0B2KX68WM',True),
     ('Biome Ultra spore probiotic (match) — Walmart','https://www.walmart.com/ip/Dynamic-Enzymes-Biome-Ultra-Spore-Probiotics-Prebiotic-30-Capsules/3517582664',True)],
    'bacillus spore probiotic capsules','Gut, probiotic, omega & fiber'),

 mk('thorne-multivitamin-alternative','Thorne Basic Nutrients 2/Day','Daily multivitamin',36,'$1.20','2 capsules/day · 60/bottle',False,
    'A complete iron-free multivitamin/mineral, all disclosed: vitamins A, C 250 mg, D3 2,000 IU, E, K1+K2 400 mcg, a full B-complex with L-5-MTHF folate and methylcobalamin B12 600 mcg, plus chelated zinc, selenium, copper, iodine, and chromium.',
    [{'name':'Generic methylated multivitamin (iron-free)','desc':'1/day','cost':17,'cls':'mod'}],
    ['Both are complete daily multivitamin/mineral formulas with overlapping ingredients across the core vitamins and minerals.','Both deliver B-vitamins in methylated forms (5-MTHF folate + methylcobalamin B12) and are iron-free — key points of similarity.','A similar intended use — filling everyday dietary nutrient gaps — at a lower monthly cost.'],
    ['Thorne uses chelated minerals (TRAACS bisglycinate/glycinate) and specific bioavailable forms; the match may use different forms and doses — check the label.','Thorne is NSF Certified for Sport (third-party tested for banned substances), which matters for competitive athletes; generics typically are not.','Dosing differs — 2 capsules/day vs 1/day — so per-serving totals vary.'],
    [{'name':'Multivitamin (fills gaps)','cls':'mod','note':'Solid for covering dietary shortfalls.'},{'name':'Methylated forms','cls':'weak','note':'Mainly benefit specific subgroups (e.g. MTHFR variants), not a universal advantage.'}],
    'Both are iron-free, so they are not appropriate where iron supplementation is needed. Fat-soluble vitamins and minerals can accumulate — don’t stack overlapping supplements; vitamin K can interact with anticoagulants.',
    ['<b style="color:var(--ink)">Consult a physician, pharmacist, or registered dietitian</b> before starting or switching if you are pregnant, nursing, on medication (especially blood thinners), or manage a health condition.'],
    [('Thorne Basic Nutrients 2/Day — brand page (price Jul 2026)','https://www.thorne.com/products/dp/basic-nutrients-2-day',True),
     ('Thorne Basic Nutrients 2/Day — Amazon listing','https://www.amazon.com/Thorne-Basic-Nutrients-Comprehensive-Bioavailability/dp/B00FOTMGTU',True),
     ('Generic methylated iron-free multivitamin (match) — Walmart','https://www.walmart.com/ip/Just-One-Daily-Methylated-Multivitamin-for-Men-Women-60-Caps-Adults-MTHFR-Support-Iron-Free-Natural-USA-Made/7660862829',True)],
    'methylated multivitamin iron free','Daily multivitamins & greens'),

 mk('goli-acv-alternative','Goli Apple Cider Vinegar Gummies','Wellness · apple cider vinegar',17,'$0.57','2 gummies/day · 60/bottle',False,
    'Apple cider vinegar (~500 mg per gummy, ~1,000 mg/day) with added vitamin B12 (~2.4 mcg/day) and folate, plus beetroot and pomegranate (those amounts are not disclosed) and ~2 g added cane sugar per daily serving.',
    [{'name':'Generic ACV gummies (1,000 mg/serving)','desc':'2 gummies/day','cost':10,'cls':'weak'}],
    ['Overlapping core ingredient — apple cider vinegar at a comparable ~1,000 mg/day, and generic gummies often add the same B12, beetroot, and pomegranate.','A similar intended use (general wellness ACV supplement) and the same 2-a-day gummy format.','A lower-cost ingredient match on the ACV itself; plain liquid ACV "with the mother" is cheaper still (~$5/mo).'],
    ['Both Goli and generic gummies add cane sugar and lack "the mother," and deliver a modest ACV dose per gummy versus a tablespoon of liquid.','Liquid ACV is far cheaper but tastes harsh and needs diluting — an important difference in convenience.','Generic gummies vary in exact B12/beetroot/pomegranate amounts and testing — check each label.'],
    [{'name':'Apple cider vinegar','cls':'weak','note':'Weak/limited human evidence; small, short, mixed studies. Not a treatment.'},{'name':'Vitamin B12','cls':'weak','note':'Helps mainly people who are actually deficient.'}],
    'Apple cider vinegar is acidic — regular use may contribute to tooth-enamel erosion and throat or stomach irritation (dilute liquid ACV). It can affect blood sugar and potassium.',
    ['<b style="color:var(--ink)">Consult a doctor or pharmacist</b> before regular use if you take diabetes/blood-sugar medication, insulin, or diuretics, have kidney issues, or are pregnant or nursing.'],
    [('Goli ACV Gummies — brand product page (price Jul 2026)','https://goli.com/products/goli-nutrition-1-bottle-of-apple-cider-vinegar-gummies',True),
     ('Goli ACV Gummies — Target listing','https://www.target.com/p/goli-nutrition-apple-cider-vinegar-vegan-gummies-60ct/-/A-83821428',True),
     ('Bragg Organic ACV with the Mother (liquid match) — Walmart','https://www.walmart.com/ip/Bragg-Organic-Raw-Apple-Cider-Vinegar-16-Ounce-1-pack/771609107',True)],
    'apple cider vinegar gummies','Gut, probiotic, omega & fiber'),

 mk('kachava-alternative','Ka’Chava Whole Body Meal','Meal replacement · superfood shake',120,'$4.00','1 shake/day · 15/bag',True,
    'A plant-protein meal shake (~25 g protein, ~6 g fiber per serving) plus "85+ superfoods" — greens, adaptogens, probiotics, and digestive enzymes bundled into proprietary blends whose individual amounts are not disclosed.',
    [{'name':'Budget plant protein powder','desc':'~25 g/day','cost':19,'cls':'mod'},{'name':'Greens powder','desc':'1 scoop/day','cost':27,'cls':'weak'},{'name':'Daily multivitamin','desc':'1/day','cost':9,'cls':'mod'}],
    ['Overlapping ingredients — both deliver ~25 g plant protein plus a greens/superfood component and added micronutrients.','A similar intended use — a once-daily plant-based shake to supplement or replace a meal.','A lower-cost ingredient match assembling the same core categories (protein + greens + multivitamin) separately.'],
    ['Ka’Chava’s superfood, adaptogen, and probiotic content is in proprietary blends with undisclosed per-ingredient doses; a DIY match can’t replicate the exact 85+ item formula, and neither can be dose-verified.','Ka’Chava is one all-in-one scoop with a single flavor system and added enzymes; the match is 2–3 products to mix and manage.','Fortification, amino-acid profile, and taste differ — important differences, not an identical substitute.'],
    [{'name':'Plant protein','cls':'mod','note':'Solid — ~25 g plant protein is a well-supported contributor to daily needs.'},{'name':'Greens powders vs vegetables','cls':'weak','note':'Do not match whole vegetables for nutrition.'},{'name':'Adaptogens & probiotics','cls':'limited','note':'Undisclosed doses prevent an evidence-based assessment.'}],
    'A meal-replacement shake is not weight-loss or disease treatment. It contains adaptogens, probiotics, and enzymes that may interact with medications or conditions.',
    ['<b style="color:var(--ink)">Consult a doctor or registered dietitian</b> before use — especially before replacing meals — if you are pregnant or nursing, on medication, have kidney issues or allergies, or manage a health condition.'],
    [('Ka’Chava — ingredients page','https://www.kachava.com/ingredients',True),
     ('Ka’Chava pricing — support doc (Jul 2026)','https://support.kachava.com/hc/en-us/articles/360045974531-How-much-does-Ka-Chava-cost',True),
     ('Ka’Chava review — Top Nutrition Coaching','https://www.topnutritioncoaching.com/blog/kachava-review',True)],
    'plant based protein powder greens','Daily multivitamins & greens'),

 mk('ancient-nutrition-alternative','Ancient Nutrition Multi Collagen Protein','Beauty · collagen',30,'$1.00','1 scoop/day · 45/tub',True,
    'A ~10 g "Multi Collagen Complex" per scoop from four sources — bovine, chicken, fish, and eggshell membrane — providing Types I, II, III, V, and X, plus added vitamin C and probiotics. The grams per source are not disclosed.',
    [{'name':'Store-brand bovine collagen peptides (Types I & III)','desc':'~10 g/day','cost':15,'cls':'mod'}],
    ['Overlapping core ingredient — both deliver hydrolyzed collagen peptides with Types I and III.','A similar intended use — marketed for skin, hair, nail, and joint support.','The store brand is a genuine lower-cost ingredient match on the primary collagen component.'],
    ['Multi-source vs single-source — Ancient Nutrition blends four animal sources; the store brand is bovine only, so it doesn’t reproduce Types II, V, or X.','Ancient Nutrition uses a proprietary blend (grams per source undisclosed) and adds vitamin C and probiotics; exact ingredient-level matching isn’t possible.','Per-scoop dose differs (~10 g vs ~6.7 g in some store brands) — measure to match.'],
    [{'name':'Collagen for skin','cls':'mod','note':'Moderate evidence for elasticity/hydration.'},{'name':'Collagen for joints','cls':'weak','note':'Weak; Type II specifically has limited evidence.'},{'name':'Collagen for hair & nails','cls':'weak','note':'Limited controlled evidence.'}],
    'Because it draws from multiple animal sources (beef, chicken, fish, egg), it carries broader allergen exposure than a single-source bovine product — check labels for fish, egg, or poultry allergies. Collagen is an incomplete protein (low in tryptophan).',
    ['<b style="color:var(--ink)">Consult a qualified healthcare professional</b> before use if you are pregnant or nursing, have a kidney condition or a protein-restricted diet, have relevant allergies, or take medications.'],
    [('Ancient Nutrition Multi Collagen Protein — Amazon listing (price Jul 2026)','https://www.amazon.com/Ancient-Nutrition-Collagen-Protein-Powder/dp/B01LXADO9Z',True),
     ('Spring Valley collagen peptides Types 1 & 3 (match) — Walmart','https://www.walmart.com/ip/Spring-Valley-Collagen-Peptides-Type-1-3-Dietary-Supplement-9-oz/806416181',True),
     ('Hydrolyzed collagen & skin — meta-analysis (PMC)','https://pmc.ncbi.nlm.nih.gov/articles/PMC10773595/',True)],
    'bovine collagen peptides unflavored','Beauty, hair, joint & immune'),

 mk('mudwtr-alternative','MUD\\WTR :rise Cacao','Coffee alternative · mushroom',40,'$1.33','1 serving/day · 30/tin',True,
    'A cacao-based coffee alternative with a masala spice blend, black tea (~35 mg caffeine), and a four-mushroom blend (lion’s mane, chaga, reishi, cordyceps). The individual mushroom amounts are not disclosed.',
    [{'name':'Organic cacao powder','desc':'1 serving/day','cost':5,'cls':'weak'},{'name':'Generic lion’s mane capsule','desc':'1/day','cost':15,'cls':'limited'}],
    ['Overlapping ingredients — both center on organic cacao plus lion’s mane.','A similar intended use — a lower-caffeine morning coffee alternative / warm cacao ritual.','A lower-cost ingredient match sourcing the same core components (cacao + lion’s mane) at a materially lower cost.'],
    ['MUD\\WTR adds a broader four-mushroom blend plus a full masala/chai spice mix and black tea; a basic cacao + lion’s mane pairing omits chaga, reishi, cordyceps and the spices.','A single pre-blended scoop vs. mixing powder and taking a separate capsule — flavor and mouthfeel won’t be identical.','MUD\\WTR doesn’t disclose individual mushroom amounts, so an exact ingredient-for-ingredient dose comparison isn’t possible.'],
    [{'name':'Functional mushrooms','cls':'limited','note':'Human evidence is limited/emerging; benefits not firmly established.'},{'name':'Cacao','cls':'weak','note':'Contains flavanols; effects generally mild.'}],
    'Functional mushrooms and cacao are generally well tolerated, but responses vary. Caffeine here is low (~35 mg).',
    ['<b style="color:var(--ink)">Consult a healthcare professional</b> before use if you have a mushroom allergy, are pregnant or nursing, or take medication (e.g. blood thinners, immune-modulating, or blood-pressure/blood-sugar drugs).'],
    [('MUD\\WTR :rise — brand product page (price Jul 2026)','https://mudwtr.com/pages/mushroom-coffee-alternative-rise',True),
     ('MUD\\WTR ingredients page','https://mudwtr.com/pages/ingredients',True),
     ('MUD\\WTR review — Innerbody','https://www.innerbody.com/mud-wtr-review',True)],
    'cacao powder lions mane mushroom','Energy drinks & mixes'),

 mk('momentous-creatine-alternative','Momentous Creatine Monohydrate','Fitness · creatine',14,'$0.47','5 g/day · 90/tub',False,
    'A single ingredient — 5 g of creatine monohydrate per serving, unflavored, no additives. Historically Creapure-sourced (verify per lot).',
    [{'name':'Bulk creatine monohydrate (Creapure)','desc':'5 g/day','cost':7,'cls':'strong'}],
    ['Both deliver the same molecule — 5 g of creatine monohydrate per serving — as a single unflavored ingredient, for a similar intended use (strength and performance).','Both are offered in Creapure-branded creatine, the same source form.','A lower-cost ingredient match at the same standard 5 g daily dose.'],
    ['Certification differs — Momentous is NSF Certified for Sport and Informed Sport (relevant for tested athletes); a bulk match is third-party lab tested but usually not sport-certified.','Sourcing — Momentous has moved some SKUs from Creapure to a proprietary "Signature Spec" creatine; confirm current sourcing on each before assuming identical origin.','The bulk match is a larger tub driving the lower per-serving cost; Momentous is a smaller premium-positioned tub.'],
    [{'name':'Creatine monohydrate','cls':'strong','note':'One of the most-studied sport-nutrition ingredients for strength, power, and lean mass.'}],
    'Creatine monohydrate is generally well tolerated in healthy adults at ~3–5 g/day; mild GI upset or water-weight gain can occur.',
    ['<b style="color:var(--ink)">Talk to a physician or registered dietitian first</b> if you have kidney disease or reduced kidney function, are pregnant or nursing, or take medication.'],
    [('Momentous Creatine Monohydrate — brand page (price Jul 2026)','https://www.livemomentous.com/products/creatine-monohydrate',True),
     ('Nutricost Creapure creatine monohydrate (match)','https://nutricost.com/products/nutricost-creapure-creatine-monohydrate-powder',True),
     ('Creatine evidence — ISSN position stand','https://jissn.biomedcentral.com/articles/10.1186/s12970-017-0173-z',True)],
    'creatine monohydrate creapure bulk','Fitness & performance'),

 mk('legion-pulse-alternative','Legion Pulse Pre-Workout','Fitness · pre-workout',53,'$1.77','1 serving/day · ~21/tub',False,
    'A fully disclosed formula (no proprietary blends): L-citrulline DL-malate ~8 g, beta-alanine ~3.6 g, betaine ~2.5 g, caffeine ~350 mg, L-theanine ~350 mg, and alpha-GPC ~300 mg per serving.',
    [{'name':'Bulk L-citrulline malate','desc':'~8 g/day','cost':7,'cls':'mod'},{'name':'Bulk beta-alanine','desc':'~3.6 g/day','cost':3,'cls':'mod'},{'name':'Bulk caffeine + betaine + theanine','desc':'daily','cost':4,'cls':'strong'}],
    ['Overlapping ingredients — a DIY stack replicates 5 of Legion’s 6 actives (citrulline malate, beta-alanine, caffeine, betaine, theanine) at similar disclosed doses.','A similar intended use — a pre-workout for energy, focus, and muscular endurance.','A lower-cost ingredient match — buying these actives in bulk costs a fraction of the finished product per month.'],
    ['DIY requires weighing and mixing each dose accurately (a gram scale) and has no ready flavor system, so taste and mixability are worse.','The match omits alpha-GPC and Legion’s flavoring; Legion arrives pre-blended and flavored.','Legion is fully label-transparent with no proprietary blends and third-party lab tested — a genuine plus versus self-sourcing multiple raw powders.'],
    [{'name':'L-citrulline','cls':'mod','note':'Moderate for exercise performance/muscular endurance.'},{'name':'Beta-alanine','cls':'mod','note':'Moderate for muscular endurance.'},{'name':'Caffeine','cls':'strong','note':'Strong for exercise performance and perceived energy.'}],
    'Caffeine here is high (~350 mg per serving — roughly 3–4 cups of coffee): possible jitters, raised heart rate, or sleep disruption; avoid late-day use. Beta-alanine commonly causes harmless tingling.',CAFF_CONSULT,
    [('Legion Pulse Pre-Workout — brand page (price Jul 2026)','https://legionathletics.com/products/supplements/pulse-pre-workout/',True),
     ('Legion Pulse review — BarBend','https://barbend.com/legion-pulse-pre-workout-review/',True),
     ('Bulk L-citrulline DL-malate (match) — BulkSupplements','https://www.bulksupplements.com/products/l-citrulline-dl-malate-2-1-pure-powder',True)],
    'pre workout citrulline beta alanine caffeine','Fitness & performance'),
]

if __name__=='__main__':
    made=[]
    for d,bucket in RESEARCH:
        with open(d['slug']+'.html','w',encoding='utf-8') as f: f.write(render_compare(d))
        swap=sum(s['cost'] for s in d['swap_rows'])
        made.append((bucket,d['name'],d['slug'],d['brand_price'],round(swap)))
        print('wrote %s.html  $%d -> $%d'%(d['slug'],d['brand_price'],round(swap)))
    print('rendered %d research pages'%len(made))
    # emit BESPOKE-style rows for pasting into build_from_sheet.py homepage list
    for bucket,name,slug,o,bu in made:
        print("ADD:  ('%s','%s','/%s.html',%d,%d),"%(bucket,name.replace("'","’"),slug,o,bu))
