#!/usr/bin/env python3
"""Canonical-URL normalization pass (2026-07-20).

The site historically emitted mixed URL forms: canonical tags + sitemap used the
.html extension while the nav/hub links used clean (extensionless) URLs, and BOTH
/slug and /slug.html returned 200. Mixed signals dilute indexing. This pass makes
the CLEAN URL the single canonical form everywhere and 301s the .html variant to it.

What it does (idempotent, safe to re-run — MUST run LAST in build_all.sh):
  1. Strip `.html` from <link rel=canonical> and og:url on every page (index -> "/").
  2. Strip `.html` from every INTERNAL link that points to a real page file
     (full-URL, absolute-path, and relative forms). External + asset links untouched.
  3. Rewrite sitemap.xml <loc> to the clean form.
  4. Write _redirects (Netlify) 301'ing every /slug.html -> /slug (and /index.html -> /).
"""
import glob, re, os

SITE = "https://blendbusters.com"

def pages():
    return sorted(f for f in glob.glob("*.html")
                  if "mockup" not in f and "standalone" not in f)

PAGE_SET = set(pages())
SLUGS = {p[:-5] for p in PAGE_SET}  # basename without .html

def clean_url(slug):
    return f"{SITE}/" if slug == "index" else f"{SITE}/{slug}"

def strip_html_in_head(s):
    # canonical + og:url -> clean
    def repl_full(m):
        attr, url = m.group(1), m.group(2)
        slug = url[len(SITE):].lstrip("/")
        slug = slug[:-5] if slug.endswith(".html") else slug
        if slug in ("", "/"): slug = "index"
        if slug not in SLUGS and slug != "index":
            return m.group(0)  # not one of our pages; leave alone
        return f'{attr}"{clean_url(slug)}"'
    s = re.sub(r'(<link rel="canonical" href=)"([^"]+)"', repl_full, s)
    s = re.sub(r'(<meta property="og:url" content=)"([^"]+)"', repl_full, s)
    return s

# internal link stripping ------------------------------------------------------
def strip_html_in_links(s):
    # 1) full-URL links: https://blendbusters.com/slug.html -> /slug
    def repl_full(m):
        slug = m.group(1)
        if slug == "index":
            return f'href="{SITE}/"'
        return f'href="{SITE}/{slug}"' if slug in SLUGS else m.group(0)
    s = re.sub(r'href="' + re.escape(SITE) + r'/([a-z0-9-]+)\.html"', repl_full, s)

    # 2) absolute-path links: /slug.html -> /slug
    def repl_abs(m):
        slug = m.group(1)
        if slug == "index":
            return 'href="/"'
        return f'href="/{slug}"' if slug in SLUGS else m.group(0)
    s = re.sub(r'href="/([a-z0-9-]+)\.html"', repl_abs, s)

    # 3) relative links: slug.html -> slug  (no leading slash, not a full URL)
    def repl_rel(m):
        slug = m.group(1)
        if slug == "index":
            return 'href="/"'
        return f'href="{slug}"' if slug in SLUGS else m.group(0)
    s = re.sub(r'href="([a-z0-9-]+)\.html"', repl_rel, s)
    return s

def process_pages():
    n = 0
    for f in PAGE_SET:
        s = open(f, encoding="utf-8").read()
        out = strip_html_in_links(strip_html_in_head(s))
        if out != s:
            open(f, "w", encoding="utf-8").write(out)
            n += 1
    return n

def fix_sitemap():
    if not os.path.exists("sitemap.xml"):
        return "sitemap.xml absent"
    xml = open("sitemap.xml", encoding="utf-8").read()
    def repl(m):
        url = m.group(1)
        slug = url[len(SITE):].lstrip("/")
        slug = slug[:-5] if slug.endswith(".html") else slug
        if slug in ("", "/"):
            return f"<loc>{SITE}/</loc>"
        return f"<loc>{clean_url(slug)}</loc>" if slug in SLUGS else m.group(0)
    xml = re.sub(r"<loc>([^<]+)</loc>", repl, xml)
    open("sitemap.xml", "w", encoding="utf-8").write(xml)
    return "sitemap.xml: <loc> normalized to clean URLs"

def write_redirects():
    lines = ["# Auto-generated by normalize_urls.py — 301 .html -> clean URL",
             "/index.html   /   301!"]
    for slug in sorted(SLUGS):
        if slug == "index":
            continue
        lines.append(f"/{slug}.html   /{slug}   301!")
    open("_redirects", "w", encoding="utf-8").write("\n".join(lines) + "\n")
    return f"_redirects: {len(lines)-2} .html->clean 301 rules"

if __name__ == "__main__":
    print(f"pages normalized: {process_pages()}")
    print(fix_sitemap())
    print(write_redirects())
